# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BliinkSampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BliinkSampleObjc

  pod 'BliinkSdk'

  target 'BliinkSampleObjcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BliinkSampleObjcUITests' do
    # Pods for testing
  end

end
